namespace OpenPrismNode.Core.Entities;

using OpenPrismNode.Core.Models;

public class EpochEntity
{
    /// <summary>
    /// Just the Epoch-Number
    /// Note: This is the primary key, but the value is not generated by the database
    /// see Fluent API
    /// </summary>
    public required int EpochNumber { get; set; }

    /// <summary>
    /// Reference to the Block-Entities
    /// </summary>
    public List<BlockEntity> BlockEntities { get; set; } = new List<BlockEntity>();

    /// <summary>
    /// Reference to the network
    /// </summary>
    public LedgerEntity LedgerEntity { get; set; }  // don't add a default value here!
    
    /// <summary>
    /// FK of the ledger
    /// </summary>
    public LedgerType Ledger { get; set; }
}